import json, urllib.request, time

GAS_URL = "https://script.google.com/macros/s/AKfycbz1MwFg8ujR1QNMDiggRTGqAKYLfTYW6FvfPiAv7-L8DWQKurHSJ_mYGr9h0eqQ5jRBrg/exec"

def gas_post(payload):
    data = json.dumps(payload).encode()
    req = urllib.request.Request(GAS_URL, data=data,
          headers={"Content-Type": "text/plain"}, method="POST")
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read().decode())

# ── Build positioning with Mary's locked language woven in ───────────────────
positioning = {
    "positioning_id":   "MP-EC-2026-001-1779241647193",
    "campaign_id":      "EC-2026-001",
    "icp_code":         "super_mom_time",
    "theme_slug":       "dinner-already-decided",
    "status":           "DRAFT",

    # ── WHO SHE IS — includes AC-013 time stat ────────────────────────────
    "who_she_is": (
        "It is 4:47 PM on a Wednesday. She has chicken thighs, baby potatoes, and green beans "
        "in the fridge from Sunday's grocery run. She is staring into the fridge for the third "
        "time today, mentally calculating if she has enough time to defrost something else. She "
        "is about to close the door and order pizza again. "
        "She spends 5-10 hours per week on food decisions — 260-520 hours per year — "
        "10-21 full days every year standing at that fridge with a blank stare."
    ),

    # ── CORE TRUTH ────────────────────────────────────────────────────────
    "core_truth": (
        "The dinner decision is not hard because she cannot cook. "
        "It is hard because no tool has ever connected what she has to what she can make in real time."
    ),

    # ── MASTER STORY ──────────────────────────────────────────────────────
    "master_story": (
        "Your kitchen is broken. Not because of you. Because no tool ever closed the loop. "
        "easyChef Pro closes the loop. Your kitchen. In command."
    ),

    # ── WHAT WE SAY ───────────────────────────────────────────────────────
    "what_we_say": (
        "Dinner is already decided. You just do not know it yet. "
        "easyChef Pro instantly matches what is in your fridge to what is on your table in 30 minutes."
    ),

    # ── FEELING SOLD ──────────────────────────────────────────────────────
    "feeling_sold": (
        "She walks into her kitchen at 5 PM and feels like she has a sous chef who already knows "
        "what is for dinner. The relief of never having to solve the dinner puzzle again — "
        "reclaiming 10-21 full days a year she used to spend deciding."
    ),

    # ── LOSS AVERSION — Mary's locked line ───────────────────────────────
    "loss_aversion_line": (
        "Every night she wings it is an evening she did not choose for her family. "
        "Approved uses: email subject · TikTok overlay · LP subheadline"
    ),

    # ── MESSAGE HIERARCHY — Mary's 4-point order ─────────────────────────
    "message_hierarchy": (
        "1. Dinner decided before she opens the fridge\n"
        "2. Founding family identity\n"
        "3. $1,336 savings (proof only — never hook)\n"
        "4. $7.99 founding price (CTA only)"
    ),

    # ── EMOTIONAL ARC ─────────────────────────────────────────────────────
    "emotional_arc": json.dumps([
        "exhausted", "frustrated", "activated",
        "curious", "relieved", "proud", "peaceful"
    ]),

    # ── PROOF POINT ───────────────────────────────────────────────────────
    "proof_point": (
        "5-10 hours per week on food decisions — 260-520 hours per year — "
        "10-21 full days annually. (AC-013, approved Mary 2026-05-19)"
    ),

    # ── STAGE 5 RETENTION JOB ─────────────────────────────────────────────
    "stage_5_retention_job": (
        "Guide her through Three-Ingredient Start (Day 0, 80% target), "
        "then First Strike on Day 7 where she cooks her first stress-free dinner (45% target), "
        "building toward Tipping Point when she has cooked 3+ meals, saved food waste once, "
        "and tracked 20+ pantry items (Day 30, 60% target AND-logic), "
        "then Paid Conversion within 7 days of Tipping Point (40% target)."
    ),

    # ── CHANNEL AFFINITY ──────────────────────────────────────────────────
    "channel_strategy": (
        "TikTok discovers → Facebook validates → Instagram aspires → community grows. "
        "Primary TikTok scene: Scene 1: Standing at fridge. 6:30 PM. Blank stare. "
        "Scene 2: Dinner already planned. Recipe open. "
        "Overlay: loss aversion line. End card: 7-day free trial."
    ),

    # ── SECONDARY PAIN ────────────────────────────────────────────────────
    "secondary_pain": (
        "Paprika and AnyList do not talk to each other — the five-app problem. "
        "App fragmentation is the real enemy."
    ),

    # ── GENERATED BY ──────────────────────────────────────────────────────
    "generated_by": "claude-sonnet-4-20250514",
    "ml_approved": False,
    "locked": False,
}

# ── 1. Save ───────────────────────────────────────────────────────────────────
print("Saving MasterPositioning MP-EC-2026-001-1779241647193...")
r_save = gas_post({"action": "master_positioning_save", "positioning": positioning})
print(f"  Save result: ok={r_save.get('ok')} — {r_save.get('positioning_id','')}")
if not r_save.get('ok'):
    print(f"  ERROR: {r_save}")
    exit(1)

time.sleep(1)

# ── 2. Lock ───────────────────────────────────────────────────────────────────
print("Locking positioning...")
r_lock = gas_post({
    "action": "master_positioning_lock",
    "positioning_id": "MP-EC-2026-001-1779241647193"
})
print(f"  Lock result: ok={r_lock.get('ok')} — status={r_lock.get('status','')}")
if r_lock.get('stage_gates_seeded'):
    print(f"  Stage gates seeded: {r_lock.get('stage_gates_seeded')}")

print("\nDone.")
print(f"  Saved:  {r_save.get('ok')}")
print(f"  Locked: {r_lock.get('ok')}")
print(f"  Status: {r_lock.get('status', 'check sheet')}")
