"""Convert remaining google.script.run calls in firebase cockpit.html"""
import sys

path = r'C:\Users\Trader\easyChef-Pro-Ops-Center\firebase-deploy\public\cockpit.html'
with open(path, 'r', encoding='utf-8') as f:
    out = f.read()

replacements = []

# ── 1. cloneAccount ──────────────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r) {\n"
    "          if (r && r.ok) {\n"
    "            document.getElementById('na-status').textContent = '✓ Created';\n"
    "            btn.textContent = '✓ Done';\n"
    "            setTimeout(function() {\n"
    "              closeNewAccountModal();\n"
    "              loadAccounts();\n"
    "            }, 800);\n"
    "          } else {\n"
    "            btn.disabled = false; btn.textContent = 'Create Account';\n"
    "            document.getElementById('na-status').textContent = 'Error: ' + ((r && r.error) || 'unknown');\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function() {\n"
    "          btn.disabled = false; btn.textContent = 'Create Account';\n"
    "          document.getElementById('na-status').textContent = 'Connection error.';\n"
    "        })\n"
    "        .cloneAccount(name, id, templateFileId || null);",
    "      gasCall({action:'clone_account', account_name:name, account_id:id, template_file_id:templateFileId||null, sheet_id:_activeSheetId})\n"
    "        .then(function(r) {\n"
    "          if (r && r.ok) {\n"
    "            document.getElementById('na-status').textContent = '✓ Created';\n"
    "            btn.textContent = '✓ Done';\n"
    "            setTimeout(function() {\n"
    "              closeNewAccountModal();\n"
    "              loadAccounts();\n"
    "            }, 800);\n"
    "          } else {\n"
    "            btn.disabled = false; btn.textContent = 'Create Account';\n"
    "            document.getElementById('na-status').textContent = 'Error: ' + ((r && r.error) || 'unknown');\n"
    "          }\n"
    "        })\n"
    "        .catch(function() {\n"
    "          btn.disabled = false; btn.textContent = 'Create Account';\n"
    "          document.getElementById('na-status').textContent = 'Connection error.';\n"
    "        });"
))

# ── 2. OB 3-branch ────────────────────────────────────────────────────────────
replacements.append((
    "      var call = google.script.run\n"
    "        .withSuccessHandler(function(r) {\n"
    "          clearInterval(ticker);\n"
    "          if (r && r.ok !== false) {\n"
    "            var parts = ['✓ Done'];\n"
    "            if (r.seeded)    { var s = r.seeded;    parts.push('Seeded: ' + (s.emails||0) + ' emails, ' + (s.landing_pages||0) + ' LPs, ' + (s.thank_you||0) + ' TY'); }\n"
    "            if (r.generated) { var g = r.generated; parts.push('Generated: ' + (g.emails||0) + ' emails, ' + (g.landing_pages||0) + ' LPs, ' + (g.thank_you||0) + ' TY'); }\n"
    "            if (r.errors && r.errors.length) parts.push('⚠ ' + r.errors.length + ' errors');\n"
    "            status.textContent = parts.join(' · ');\n"
    "            btn.textContent = '✓ Done';\n"
    "            // Reload calendar to show new OB assets\n"
    "            calData = null; loadCalendar();\n"
    "          } else {\n"
    "            status.textContent = 'Error: ' + ((r && r.error) || 'unknown');\n"
    "            btn.disabled = false; btn.textContent = 'Run';\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function() {\n"
    "          clearInterval(ticker);\n"
    "          status.textContent = 'Connection error.';\n"
    "          btn.disabled = false; btn.textContent = 'Run';\n"
    "        });\n"
    "      if (fnName === 'runOBCampaignFull')   call.runOBCampaignFull(campaignId, _activeSheetId, icpCodes);\n"
    "      else if (fnName === 'seedOBCalendar') call.seedOBCalendar(campaignId, _activeSheetId, false, icpCodes);\n"
    "      else                                  call.generateOBCampaign(campaignId, _activeSheetId, icpCodes);",
    "      var _obActs = {runOBCampaignFull:'run_ob_campaign_full', seedOBCalendar:'seed_ob_calendar', generateOBCampaign:'generate_ob_campaign'};\n"
    "      gasCall({action:_obActs[fnName]||'run_ob_campaign_full', campaign_id:campaignId, sheet_id:_activeSheetId, icp_codes:icpCodes||null})\n"
    "        .then(function(r) {\n"
    "          clearInterval(ticker);\n"
    "          if (r && r.ok !== false) {\n"
    "            var parts = ['✓ Done'];\n"
    "            if (r.seeded)    { var s = r.seeded;    parts.push('Seeded: ' + (s.emails||0) + ' emails, ' + (s.landing_pages||0) + ' LPs, ' + (s.thank_you||0) + ' TY'); }\n"
    "            if (r.generated) { var g = r.generated; parts.push('Generated: ' + (g.emails||0) + ' emails, ' + (g.landing_pages||0) + ' LPs, ' + (g.thank_you||0) + ' TY'); }\n"
    "            if (r.errors && r.errors.length) parts.push('⚠ ' + r.errors.length + ' errors');\n"
    "            status.textContent = parts.join(' · ');\n"
    "            btn.textContent = '✓ Done';\n"
    "            // Reload calendar to show new OB assets\n"
    "            calData = null; loadCalendar();\n"
    "          } else {\n"
    "            status.textContent = 'Error: ' + ((r && r.error) || 'unknown');\n"
    "            btn.disabled = false; btn.textContent = 'Run';\n"
    "          }\n"
    "        })\n"
    "        .catch(function() {\n"
    "          clearInterval(ticker);\n"
    "          status.textContent = 'Connection error.';\n"
    "          btn.disabled = false; btn.textContent = 'Run';\n"
    "        });"
))

# ── 3. checkAccountSetup ──────────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r) {\n"
    "          _setupStatus = (r && r.ok) ? r : null;\n"
    "          // Re-render dashboard if it's already showing so checklist updates immediately\n"
    "          if (dashData && activeTab === 'dash') {\n"
    "            var all = getAllPosts();\n"
    "            renderDash(dashData, all);\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function() { _setupStatus = null; })\n"
    "        .checkAccountSetup(_activeSheetId);",
    "      gasCall({action:'check_account_setup', sheet_id:_activeSheetId})\n"
    "        .then(function(r) {\n"
    "          _setupStatus = (r && r.ok) ? r : null;\n"
    "          // Re-render dashboard if it's already showing so checklist updates immediately\n"
    "          if (dashData && activeTab === 'dash') {\n"
    "            var all = getAllPosts();\n"
    "            renderDash(dashData, all);\n"
    "          }\n"
    "        })\n"
    "        .catch(function() { _setupStatus = null; });"
))

# ── 4. getEmailSequences (loadSeqMeta) ────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(!r||!r.ok) return;\n"
    "          var meta = {};\n"
    "          (r.sequences||[]).forEach(function(s){\n"
    "            var code = s.sequence_code; if(!code) return;\n"
    "            if(!meta[code]) meta[code] = {emails:0, days:[], funnel:[], trigger:'', icp_code:'', segment:'', status:'', target_word_count:''};\n"
    "            meta[code].emails++;\n"
    "            if(s.send_day !== undefined && s.send_day !== '') meta[code].days.push(Number(s.send_day));\n"
    "            if(s.funnel_stage && meta[code].funnel.indexOf(s.funnel_stage) === -1) meta[code].funnel.push(s.funnel_stage);\n"
    "            if(!meta[code].trigger && s.trigger_event) meta[code].trigger = s.trigger_event;\n"
    "            if(!meta[code].icp_code          && s.icp_code)          meta[code].icp_code = s.icp_code;\n"
    "            if(!meta[code].segment           && s.segment)           meta[code].segment  = s.segment;\n"
    "            if(!meta[code].status            && s.status)            meta[code].status   = s.status;\n"
    "            if(!meta[code].target_word_count && s.target_word_count) meta[code].target_word_count = s.target_word_count;\n"
    "          });\n"
    "          // format days as range string\n"
    "          Object.keys(meta).forEach(function(code){\n"
    "            var days = meta[code].days.sort(function(a,b){return a-b;});\n"
    "            if(!days.length){ meta[code].daysStr = '—'; return; }\n"
    "            meta[code].daysStr = days.length===1 ? 'Day '+days[0] : 'Days '+days[0]+'–'+days[days.length-1];\n"
    "          });\n"
    "          _seqMeta = meta;\n"
    "          // also index every individual row by id for post-detail lookups\n"
    "          _seqEmailCache = {};\n"
    "          (r.sequences||[]).forEach(function(s){ if(s.id) _seqEmailCache[s.id] = s; });\n"
    "        })\n"
    "        .withFailureHandler(function(){})\n"
    "        .getEmailSequences(cid);",
    "      gasCall({action:'email_sequences_read', campaign_id:cid, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(!r||!r.ok) return;\n"
    "          var meta = {};\n"
    "          (r.sequences||[]).forEach(function(s){\n"
    "            var code = s.sequence_code; if(!code) return;\n"
    "            if(!meta[code]) meta[code] = {emails:0, days:[], funnel:[], trigger:'', icp_code:'', segment:'', status:'', target_word_count:''};\n"
    "            meta[code].emails++;\n"
    "            if(s.send_day !== undefined && s.send_day !== '') meta[code].days.push(Number(s.send_day));\n"
    "            if(s.funnel_stage && meta[code].funnel.indexOf(s.funnel_stage) === -1) meta[code].funnel.push(s.funnel_stage);\n"
    "            if(!meta[code].trigger && s.trigger_event) meta[code].trigger = s.trigger_event;\n"
    "            if(!meta[code].icp_code          && s.icp_code)          meta[code].icp_code = s.icp_code;\n"
    "            if(!meta[code].segment           && s.segment)           meta[code].segment  = s.segment;\n"
    "            if(!meta[code].status            && s.status)            meta[code].status   = s.status;\n"
    "            if(!meta[code].target_word_count && s.target_word_count) meta[code].target_word_count = s.target_word_count;\n"
    "          });\n"
    "          // format days as range string\n"
    "          Object.keys(meta).forEach(function(code){\n"
    "            var days = meta[code].days.sort(function(a,b){return a-b;});\n"
    "            if(!days.length){ meta[code].daysStr = '—'; return; }\n"
    "            meta[code].daysStr = days.length===1 ? 'Day '+days[0] : 'Days '+days[0]+'–'+days[days.length-1];\n"
    "          });\n"
    "          _seqMeta = meta;\n"
    "          // also index every individual row by id for post-detail lookups\n"
    "          _seqEmailCache = {};\n"
    "          (r.sequences||[]).forEach(function(s){ if(s.id) _seqEmailCache[s.id] = s; });\n"
    "        })\n"
    "        .catch(function(){});"
))

# ── 5. createLPEntry ──────────────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r) {\n"
    "          btn.disabled = false; btn.textContent = 'Create LP Entry →';\n"
    "          if (!r || !r.ok) { status.innerHTML = '<span style=\"color:#dc2626\">Error: ' + ((r && r.error) || 'unknown') + '</span>'; return; }\n"
    "          _lpWizard.lp = r.lp;\n"
    "          status.innerHTML = '<span style=\"color:#16a34a\">✓ Created: <strong>' + r.lp.id + '</strong></span>';\n"
    "          document.getElementById('lps2-lp-label').textContent = r.lp.id;\n"
    "          document.getElementById('lps2-url-label').textContent = r.lp.full_url || '—';\n"
    "          _unlockLPStep(2);\n"
    "          _refreshLPFunnel();\n"
    "        })\n"
    "        .withFailureHandler(function() {\n"
    "          btn.disabled = false; btn.textContent = 'Create LP Entry →';\n"
    "          status.innerHTML = '<span style=\"color:#dc2626\">Connection error.</span>';\n"
    "        })\n"
    "        .createLPEntry({\n"
    "          campaign_id:    cid,\n"
    "          slug:           slug,\n"
    "          full_url:       url,\n"
    "          lp_variant:     document.getElementById('lps1-variant').value,\n"
    "          page_type:      document.getElementById('lps1-type').value,\n"
    "          icp_codes:      (document.getElementById('lps1-icp').value || '').trim(),\n"
    "          campaign_angle: (document.getElementById('lps1-angle').value || '').trim(),\n"
    "          thank_you_url:  (document.getElementById('lps1-ty').value || '').trim()\n"
    "        });",
    "      gasCall({action:'create_lp_entry', campaign_id:cid, slug:slug, full_url:url,\n"
    "          lp_variant:     document.getElementById('lps1-variant').value,\n"
    "          page_type:      document.getElementById('lps1-type').value,\n"
    "          icp_codes:      (document.getElementById('lps1-icp').value || '').trim(),\n"
    "          campaign_angle: (document.getElementById('lps1-angle').value || '').trim(),\n"
    "          thank_you_url:  (document.getElementById('lps1-ty').value || '').trim(),\n"
    "          sheet_id:       _activeSheetId})\n"
    "        .then(function(r) {\n"
    "          btn.disabled = false; btn.textContent = 'Create LP Entry →';\n"
    "          if (!r || !r.ok) { status.innerHTML = '<span style=\"color:#dc2626\">Error: ' + ((r && r.error) || 'unknown') + '</span>'; return; }\n"
    "          _lpWizard.lp = r.lp;\n"
    "          status.innerHTML = '<span style=\"color:#16a34a\">✓ Created: <strong>' + r.lp.id + '</strong></span>';\n"
    "          document.getElementById('lps2-lp-label').textContent = r.lp.id;\n"
    "          document.getElementById('lps2-url-label').textContent = r.lp.full_url || '—';\n"
    "          _unlockLPStep(2);\n"
    "          _refreshLPFunnel();\n"
    "        })\n"
    "        .catch(function() {\n"
    "          btn.disabled = false; btn.textContent = 'Create LP Entry →';\n"
    "          status.innerHTML = '<span style=\"color:#dc2626\">Connection error.</span>';\n"
    "        });"
))

# ── 6. generateDLsForLP ───────────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r) {\n"
    "          btn.disabled = false; btn.textContent = 'Generate Deep Links →';\n"
    "          if (!r || !r.ok) { status.innerHTML = '<span style=\"color:#dc2626\">Error: ' + ((r && r.error) || 'unknown') + '</span>'; return; }\n"
    "          _lpWizard.dls = r.dl_ids;\n"
    "          var ids = r.dl_ids.map(function(d) { return d.dl_id; }).join(', ');\n"
    "          status.innerHTML = '<span style=\"color:#16a34a\">✓ ' + r.count + ' DL_IDs generated: <strong>' + ids + '</strong></span>';\n"
    "          _unlockLPStep(3);\n"
    "          _refreshLPFunnel();\n"
    "        })\n"
    "        .withFailureHandler(function() {\n"
    "          btn.disabled = false; btn.textContent = 'Generate Deep Links →';\n"
    "          status.innerHTML = '<span style=\"color:#dc2626\">Connection error.</span>';\n"
    "        })\n"
    "        .generateDLsForLP({\n"
    "          campaign_id: _lpWizard.lp.campaigns_using,\n"
    "          lp_id:       _lpWizard.lp.id,\n"
    "          full_url:    _lpWizard.lp.full_url,\n"
    "          lp_variant:  _lpWizard.lp.lp_variant,\n"
    "          icp_code:    _lpWizard.lp.icp_codes,\n"
    "          platforms:   platforms\n"
    "        });",
    "      gasCall({action:'generate_dls_for_lp',\n"
    "          campaign_id: _lpWizard.lp.campaigns_using,\n"
    "          lp_id:       _lpWizard.lp.id,\n"
    "          full_url:    _lpWizard.lp.full_url,\n"
    "          lp_variant:  _lpWizard.lp.lp_variant,\n"
    "          icp_code:    _lpWizard.lp.icp_codes,\n"
    "          platforms:   platforms,\n"
    "          sheet_id:    _activeSheetId})\n"
    "        .then(function(r) {\n"
    "          btn.disabled = false; btn.textContent = 'Generate Deep Links →';\n"
    "          if (!r || !r.ok) { status.innerHTML = '<span style=\"color:#dc2626\">Error: ' + ((r && r.error) || 'unknown') + '</span>'; return; }\n"
    "          _lpWizard.dls = r.dl_ids;\n"
    "          var ids = r.dl_ids.map(function(d) { return d.dl_id; }).join(', ');\n"
    "          status.innerHTML = '<span style=\"color:#16a34a\">✓ ' + r.count + ' DL_IDs generated: <strong>' + ids + '</strong></span>';\n"
    "          _unlockLPStep(3);\n"
    "          _refreshLPFunnel();\n"
    "        })\n"
    "        .catch(function() {\n"
    "          btn.disabled = false; btn.textContent = 'Generate Deep Links →';\n"
    "          status.innerHTML = '<span style=\"color:#dc2626\">Connection error.</span>';\n"
    "        });"
))

# ── 7. generateLPSpine ────────────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r) {\n"
    "          btn.disabled = false; btn.textContent = 'Generate LP Copy →';\n"
    "          if (!r || !r.ok) { status.innerHTML = '<span style=\"color:#dc2626\">Error: ' + ((r && r.error) || 'unknown') + '</span>'; return; }\n"
    "          _lpWizard.copy = r;\n"
    "          var secs = r.sections_generated || (r.spine ? Object.keys(r.spine).length : '?');\n"
    "          status.innerHTML = '<span style=\"color:#16a34a\">✓ ' + secs + ' sections generated and written to LandingPages tab.</span>';\n"
    "          _unlockLPStep(4);\n"
    "          // Pre-fill Convert ID from brief if available\n"
    "          var cid = document.getElementById('lps4-convert-id');\n"
    "          if (cid && !cid.value && r.ab_experiment_id) cid.value = r.ab_experiment_id;\n"
    "        })\n"
    "        .withFailureHandler(function() {\n"
    "          btn.disabled = false; btn.textContent = 'Generate LP Copy →';\n"
    "          status.innerHTML = '<span style=\"color:#dc2626\">Connection error.</span>';\n"
    "        })\n"
    "        .generateLPSpine(_lpWizard.lp.campaigns_using, { lp_variant: _lpWizard.lp.lp_variant, icp_code: _lpWizard.lp.icp_codes });",
    "      gasCall({action:'generate_lp_spine', campaign_id:_lpWizard.lp.campaigns_using, lp_variant:_lpWizard.lp.lp_variant, icp_code:_lpWizard.lp.icp_codes, sheet_id:_activeSheetId})\n"
    "        .then(function(r) {\n"
    "          btn.disabled = false; btn.textContent = 'Generate LP Copy →';\n"
    "          if (!r || !r.ok) { status.innerHTML = '<span style=\"color:#dc2626\">Error: ' + ((r && r.error) || 'unknown') + '</span>'; return; }\n"
    "          _lpWizard.copy = r;\n"
    "          var secs = r.sections_generated || (r.spine ? Object.keys(r.spine).length : '?');\n"
    "          status.innerHTML = '<span style=\"color:#16a34a\">✓ ' + secs + ' sections generated and written to LandingPages tab.</span>';\n"
    "          _unlockLPStep(4);\n"
    "          // Pre-fill Convert ID from brief if available\n"
    "          var cid = document.getElementById('lps4-convert-id');\n"
    "          if (cid && !cid.value && r.ab_experiment_id) cid.value = r.ab_experiment_id;\n"
    "        })\n"
    "        .catch(function() {\n"
    "          btn.disabled = false; btn.textContent = 'Generate LP Copy →';\n"
    "          status.innerHTML = '<span style=\"color:#dc2626\">Connection error.</span>';\n"
    "        });"
))

# ── 8. updateLPEntry ──────────────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r) {\n"
    "          btn.disabled = false; btn.textContent = 'Save Tracking →';\n"
    "          if (!r || !r.ok) { status.innerHTML = '<span style=\"color:#dc2626\">Error: ' + ((r && r.error) || 'unknown') + '</span>'; return; }\n"
    "          status.innerHTML = '<span style=\"color:#16a34a\">✓ Tracking IDs saved to LP record.</span>';\n"
    "          _refreshLPFunnel();\n"
    "        })\n"
    "        .withFailureHandler(function() {\n"
    "          btn.disabled = false; btn.textContent = 'Save Tracking →';\n"
    "          status.innerHTML = '<span style=\"color:#dc2626\">Connection error.</span>';\n"
    "        })\n"
    "        .updateLPEntry({\n"
    "          id:                    _lpWizard.lp.id,\n"
    "          tracking_convert_id:   (document.getElementById('lps4-convert-id').value  || '').trim(),\n"
    "          convert_experiment_id: (document.getElementById('lps4-convert-id').value  || '').trim(),\n"
    "          convert_installed:     document.getElementById('lps4-convert-on').checked,\n"
    "          tracking_ga4_id:       (document.getElementById('lps4-ga4-id').value      || '').trim(),\n"
    "          ga4_installed:         document.getElementById('lps4-ga4-on').checked,\n"
    "          tracking_clarity_id:   (document.getElementById('lps4-clarity-id').value  || '').trim(),\n"
    "          clarity_installed:     document.getElementById('lps4-clarity-on').checked\n"
    "        });",
    "      gasCall({action:'update_lp_entry',\n"
    "          id:                    _lpWizard.lp.id,\n"
    "          tracking_convert_id:   (document.getElementById('lps4-convert-id').value  || '').trim(),\n"
    "          convert_experiment_id: (document.getElementById('lps4-convert-id').value  || '').trim(),\n"
    "          convert_installed:     document.getElementById('lps4-convert-on').checked,\n"
    "          tracking_ga4_id:       (document.getElementById('lps4-ga4-id').value      || '').trim(),\n"
    "          ga4_installed:         document.getElementById('lps4-ga4-on').checked,\n"
    "          tracking_clarity_id:   (document.getElementById('lps4-clarity-id').value  || '').trim(),\n"
    "          clarity_installed:     document.getElementById('lps4-clarity-on').checked,\n"
    "          sheet_id:              _activeSheetId})\n"
    "        .then(function(r) {\n"
    "          btn.disabled = false; btn.textContent = 'Save Tracking →';\n"
    "          if (!r || !r.ok) { status.innerHTML = '<span style=\"color:#dc2626\">Error: ' + ((r && r.error) || 'unknown') + '</span>'; return; }\n"
    "          status.innerHTML = '<span style=\"color:#16a34a\">✓ Tracking IDs saved to LP record.</span>';\n"
    "          _refreshLPFunnel();\n"
    "        })\n"
    "        .catch(function() {\n"
    "          btn.disabled = false; btn.textContent = 'Save Tracking →';\n"
    "          status.innerHTML = '<span style=\"color:#dc2626\">Connection error.</span>';\n"
    "        });"
))

# ── 9. getAllCampaignFunnels ───────────────────────────────────────────────────
replacements.append((
    "        google.script.run\n"
    "          .withSuccessHandler(function(r) {\n"
    "            var w = document.getElementById('lp-funnel-wrap');\n"
    "            if (!w) return;\n"
    "            if (!r || !r.ok || !r.funnels || !r.funnels.length) {\n"
    "              w.innerHTML = '<div style=\"color:#aaa;font-size:12px;padding:12px 0\">No campaigns registered yet.</div>';\n"
    "              return;\n"
    "            }\n"
    "            w.innerHTML = r.funnels.map(function(item) {\n"
    "              return _renderFunnelBlock(item.account_id, item.account_name, item.funnel);\n"
    "            }).join('');\n"
    "          })\n"
    "          .withFailureHandler(function() {\n"
    "            var w = document.getElementById('lp-funnel-wrap');\n"
    "            if (w) w.innerHTML = '<div style=\"color:#dc2626;font-size:12px;padding:12px 0\">Failed to load funnels.</div>';\n"
    "          })\n"
    "          .getAllCampaignFunnels();",
    "        gasCall({action:'get_all_funnels', sheet_id:_activeSheetId})\n"
    "          .then(function(r) {\n"
    "            var w = document.getElementById('lp-funnel-wrap');\n"
    "            if (!w) return;\n"
    "            if (!r || !r.ok || !r.funnels || !r.funnels.length) {\n"
    "              w.innerHTML = '<div style=\"color:#aaa;font-size:12px;padding:12px 0\">No campaigns registered yet.</div>';\n"
    "              return;\n"
    "            }\n"
    "            w.innerHTML = r.funnels.map(function(item) {\n"
    "              return _renderFunnelBlock(item.account_id, item.account_name, item.funnel);\n"
    "            }).join('');\n"
    "          })\n"
    "          .catch(function() {\n"
    "            var w = document.getElementById('lp-funnel-wrap');\n"
    "            if (w) w.innerHTML = '<div style=\"color:#dc2626;font-size:12px;padding:12px 0\">Failed to load funnels.</div>';\n"
    "          });"
))

# ── 10. getCampaignFunnel ─────────────────────────────────────────────────────
replacements.append((
    "        google.script.run\n"
    "          .withSuccessHandler(function(r) {\n"
    "            var w = document.getElementById('lp-funnel-wrap');\n"
    "            if (!w) return;\n"
    "            if (!r || !r.ok) { w.innerHTML = '<div style=\"color:#dc2626;font-size:12px;padding:12px 0\">Failed to load funnel.</div>'; return; }\n"
    "            w.innerHTML = _renderFunnelBlock(_activeCampaign, _activeCampaign, r);\n"
    "          })\n"
    "          .withFailureHandler(function() {\n"
    "            var w = document.getElementById('lp-funnel-wrap');\n"
    "            if (w) w.innerHTML = '<div style=\"color:#dc2626;font-size:12px;padding:12px 0\">Failed to load funnel.</div>';\n"
    "          })\n"
    "          .getCampaignFunnel(_activeCampaign);",
    "        gasCall({action:'get_campaign_funnel', campaign_id:_activeCampaign, sheet_id:_activeSheetId})\n"
    "          .then(function(r) {\n"
    "            var w = document.getElementById('lp-funnel-wrap');\n"
    "            if (!w) return;\n"
    "            if (!r || !r.ok) { w.innerHTML = '<div style=\"color:#dc2626;font-size:12px;padding:12px 0\">Failed to load funnel.</div>'; return; }\n"
    "            w.innerHTML = _renderFunnelBlock(_activeCampaign, _activeCampaign, r);\n"
    "          })\n"
    "          .catch(function() {\n"
    "            var w = document.getElementById('lp-funnel-wrap');\n"
    "            if (w) w.innerHTML = '<div style=\"color:#dc2626;font-size:12px;padding:12px 0\">Failed to load funnel.</div>';\n"
    "          });"
))

# ── 11. fixDuplicateHooksAction ───────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(r&&r.ok&&r.result&&r.result.fixed>0){\n"
    "            btn.textContent='✓ Fixed '+r.result.fixed;\n"
    "            btn.style.background='#f0fdf4';btn.style.color='#16a34a';btn.style.borderColor='#16a34a';\n"
    "            // Reload calData so new hooks show on next popup open\n"
    "            loadCalendar();\n"
    "          } else {\n"
    "            btn.textContent='Error';btn.disabled=false;\n"
    "            alert('Fix failed: '+(r&&r.result&&r.result.error||'unknown error'));\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(e){btn.textContent='Error';btn.disabled=false;alert('Fix failed: '+e);})\n"
    "        .fixDuplicateHooksAction(dateKey,_activeCampaign);",
    "      gasCall({action:'fix_duplicate_hooks', date_key:dateKey, campaign_id:_activeCampaign, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(r&&r.ok&&r.result&&r.result.fixed>0){\n"
    "            btn.textContent='✓ Fixed '+r.result.fixed;\n"
    "            btn.style.background='#f0fdf4';btn.style.color='#16a34a';btn.style.borderColor='#16a34a';\n"
    "            // Reload calData so new hooks show on next popup open\n"
    "            loadCalendar();\n"
    "          } else {\n"
    "            btn.textContent='Error';btn.disabled=false;\n"
    "            alert('Fix failed: '+(r&&r.result&&r.result.error||'unknown error'));\n"
    "          }\n"
    "        })\n"
    "        .catch(function(e){btn.textContent='Error';btn.disabled=false;alert('Fix failed: '+e);});"
))

# ── 12. getTemplates (template picker modal) ──────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r) {\n"
    "          _renderTPList((r && r.ok) ? (r.templates || []) : []);\n"
    "        })\n"
    "        .withFailureHandler(function() {\n"
    "          document.getElementById('tp-list').innerHTML = '<div style=\"color:#dc2626;font-size:12px;text-align:center;padding:16px 0\">Failed to load templates.</div>';\n"
    "        })\n"
    "        .getTemplates();",
    "      gasCall({action:'get_templates', sheet_id:_activeSheetId})\n"
    "        .then(function(r) {\n"
    "          _renderTPList((r && r.ok) ? (r.templates || []) : []);\n"
    "        })\n"
    "        .catch(function() {\n"
    "          document.getElementById('tp-list').innerHTML = '<div style=\"color:#dc2626;font-size:12px;text-align:center;padding:16px 0\">Failed to load templates.</div>';\n"
    "        });"
))

# ── 13. confirmMove / processRequest move_asset ───────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          document.getElementById('move-overlay').classList.remove('open');\n"
    "          _pendingMove=null;\n"
    "          if(r&&r.ok){\n"
    "            _applyMoveLocally(m.assetId, m.fromDate, m.toDate);\n"
    "            _showMoveToast('Moved to '+_fmtMoveDate(m.toDate));\n"
    "          } else {\n"
    "            alert('Move failed: '+(r&&r.error?r.error:'Unknown error'));\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(err){\n"
    "          document.getElementById('move-overlay').classList.remove('open');\n"
    "          _pendingMove=null;\n"
    "          alert('Move failed: '+err.message);\n"
    "        })\n"
    "        .processRequest({action:'move_asset', asset_id:m.assetId, calendar_id:m.calendarId, new_date:m.toDate});",
    "      gasCall({action:'move_asset', asset_id:m.assetId, calendar_id:m.calendarId, new_date:m.toDate, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          document.getElementById('move-overlay').classList.remove('open');\n"
    "          _pendingMove=null;\n"
    "          if(r&&r.ok){\n"
    "            _applyMoveLocally(m.assetId, m.fromDate, m.toDate);\n"
    "            _showMoveToast('Moved to '+_fmtMoveDate(m.toDate));\n"
    "          } else {\n"
    "            alert('Move failed: '+(r&&r.error?r.error:'Unknown error'));\n"
    "          }\n"
    "        })\n"
    "        .catch(function(err){\n"
    "          document.getElementById('move-overlay').classList.remove('open');\n"
    "          _pendingMove=null;\n"
    "          alert('Move failed: '+(err&&err.message?err.message:String(err)));\n"
    "        });"
))

# ── 14. generateDesignForAsset ────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(r&&r.ok&&r.url){\n"
    "            if(POST_REGISTRY[assetId])POST_REGISTRY[assetId].claude_design_url=r.url;\n"
    "            if(msg){msg.style.color='#32d74b';msg.textContent='✓ Design generated';}\n"
    "            setTimeout(function(){openPostModal(assetId);},600);\n"
    "          } else {\n"
    "            var errMsg=(r&&r.error)||'unknown error';\n"
    "            if(btn){btn.disabled=false;btn.innerHTML='❆ Generate Design<span class=\"pm-link-tag\">ai</span>';}\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+errMsg;}\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(err){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='❆ Generate Design<span class=\"pm-link-tag\">ai</span>';}\n"
    "          if(msg){msg.style.color='#ff453a';msg.textContent='Connection error: '+(err&&err.message?err.message:String(err));}\n"
    "        })\n"
    "        .generateDesignForAsset(assetId);",
    "      gasCall({action:'generate_design_for_asset', asset_id:assetId, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(r&&r.ok&&r.url){\n"
    "            if(POST_REGISTRY[assetId])POST_REGISTRY[assetId].claude_design_url=r.url;\n"
    "            if(msg){msg.style.color='#32d74b';msg.textContent='✓ Design generated';}\n"
    "            setTimeout(function(){openPostModal(assetId);},600);\n"
    "          } else {\n"
    "            var errMsg=(r&&r.error)||'unknown error';\n"
    "            if(btn){btn.disabled=false;btn.innerHTML='❆ Generate Design<span class=\"pm-link-tag\">ai</span>';}\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+errMsg;}\n"
    "          }\n"
    "        })\n"
    "        .catch(function(err){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='❆ Generate Design<span class=\"pm-link-tag\">ai</span>';}\n"
    "          if(msg){msg.style.color='#ff453a';msg.textContent='Connection error: '+(err&&err.message?err.message:String(err));}\n"
    "        });"
))

# ── 15. getClaudeDesignPrompt ─────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='⍘ Claude Design<span class=\"pm-link-tag\">claude</span>';}\n"
    "          if(r&&r.ok&&r.prompt){\n"
    "            navigator.clipboard.writeText(r.prompt).then(function(){\n"
    "              if(msg){msg.style.color='#32d74b';msg.textContent='✓ Copied — paste into Claude.ai Design';}\n"
    "            }).catch(function(){\n"
    "              var ta=document.createElement('textarea');ta.value=r.prompt;\n"
    "              document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);\n"
    "              if(msg){msg.style.color='#32d74b';msg.textContent='✓ Copied — paste into Claude.ai Design';}\n"
    "            });\n"
    "          } else {\n"
    "            var errMsg=(r&&r.error)||'unknown error';\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+errMsg;}\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(err){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='⍘ Claude Design<span class=\"pm-link-tag\">claude</span>';}\n"
    "          if(msg){msg.style.color='#ff453a';msg.textContent='Connection error: '+(err&&err.message?err.message:String(err));}\n"
    "        })\n"
    "        .getClaudeDesignPrompt(assetId);",
    "      gasCall({action:'get_claude_design_prompt', asset_id:assetId, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='⍘ Claude Design<span class=\"pm-link-tag\">claude</span>';}\n"
    "          if(r&&r.ok&&r.prompt){\n"
    "            navigator.clipboard.writeText(r.prompt).then(function(){\n"
    "              if(msg){msg.style.color='#32d74b';msg.textContent='✓ Copied — paste into Claude.ai Design';}\n"
    "            }).catch(function(){\n"
    "              var ta=document.createElement('textarea');ta.value=r.prompt;\n"
    "              document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);\n"
    "              if(msg){msg.style.color='#32d74b';msg.textContent='✓ Copied — paste into Claude.ai Design';}\n"
    "            });\n"
    "          } else {\n"
    "            var errMsg=(r&&r.error)||'unknown error';\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+errMsg;}\n"
    "          }\n"
    "        })\n"
    "        .catch(function(err){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='⍘ Claude Design<span class=\"pm-link-tag\">claude</span>';}\n"
    "          if(msg){msg.style.color='#ff453a';msg.textContent='Connection error: '+(err&&err.message?err.message:String(err));}\n"
    "        });"
))

# ── 16. generateEmailBody ─────────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(r&&r.ok&&r.full_email_body){\n"
    "            if(POST_REGISTRY[assetId])POST_REGISTRY[assetId].full_email_body=r.full_email_body;\n"
    "            if(msg){msg.style.color='#32d74b';msg.textContent='✓ Email written — '+r.word_count+' words';}\n"
    "            setTimeout(function(){openPostModal(assetId);},600);\n"
    "          } else {\n"
    "            var errMsg=(r&&r.error)||'unknown error';\n"
    "            if(btn){btn.disabled=false;btn.innerHTML='❆ Write Email<span class=\"pm-link-tag\">ai</span>';}\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+errMsg;}\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(err){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='❆ Write Email<span class=\"pm-link-tag\">ai</span>';}\n"
    "          if(msg){msg.style.color='#ff453a';msg.textContent='Connection error: '+(err&&err.message?err.message:String(err));}\n"
    "        })\n"
    "        .generateEmailBody(assetId);",
    "      gasCall({action:'generate_email_body', asset_id:assetId, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(r&&r.ok&&r.full_email_body){\n"
    "            if(POST_REGISTRY[assetId])POST_REGISTRY[assetId].full_email_body=r.full_email_body;\n"
    "            if(msg){msg.style.color='#32d74b';msg.textContent='✓ Email written — '+r.word_count+' words';}\n"
    "            setTimeout(function(){openPostModal(assetId);},600);\n"
    "          } else {\n"
    "            var errMsg=(r&&r.error)||'unknown error';\n"
    "            if(btn){btn.disabled=false;btn.innerHTML='❆ Write Email<span class=\"pm-link-tag\">ai</span>';}\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+errMsg;}\n"
    "          }\n"
    "        })\n"
    "        .catch(function(err){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='❆ Write Email<span class=\"pm-link-tag\">ai</span>';}\n"
    "          if(msg){msg.style.color='#ff453a';msg.textContent='Connection error: '+(err&&err.message?err.message:String(err));}\n"
    "        });"
))

# ── 17. saveDesignToGithub ────────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(r&&r.ok&&r.url){\n"
    "            if(msg){msg.style.color='#32d74b';msg.textContent='✓ Live at '+r.url;}\n"
    "            if(btn){btn.disabled=false;btn.innerHTML='✓ On GitHub<span class=\"pm-link-tag\">pages</span>';}\n"
    "          } else {\n"
    "            var e=(r&&r.error)||'unknown';\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+e;}\n"
    "            if(btn){btn.disabled=false;btn.innerHTML='↑ GitHub<span class=\"pm-link-tag\">pages</span>';}\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(err){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='↑ GitHub<span class=\"pm-link-tag\">pages</span>';}\n"
    "          if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+(err&&err.message?err.message:String(err));}\n"
    "        })\n"
    "        .saveDesignToGithub(assetId);",
    "      gasCall({action:'save_design_to_github', asset_id:assetId, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(r&&r.ok&&r.url){\n"
    "            if(msg){msg.style.color='#32d74b';msg.textContent='✓ Live at '+r.url;}\n"
    "            if(btn){btn.disabled=false;btn.innerHTML='✓ On GitHub<span class=\"pm-link-tag\">pages</span>';}\n"
    "          } else {\n"
    "            var e=(r&&r.error)||'unknown';\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+e;}\n"
    "            if(btn){btn.disabled=false;btn.innerHTML='↑ GitHub<span class=\"pm-link-tag\">pages</span>';}\n"
    "          }\n"
    "        })\n"
    "        .catch(function(err){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='↑ GitHub<span class=\"pm-link-tag\">pages</span>';}\n"
    "          if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+(err&&err.message?err.message:String(err));}\n"
    "        });"
))

# ── 18. getDesignHtml ─────────────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='⍘ Copy HTML<span class=\"pm-link-tag\">claude</span>';}\n"
    "          if(r&&r.html){\n"
    "            var text=r.html;\n"
    "            if(navigator.clipboard&&navigator.clipboard.writeText){\n"
    "              navigator.clipboard.writeText(text).then(function(){\n"
    "                if(btn)btn.innerHTML='✓ Copied!<span class=\"pm-link-tag\">claude</span>';\n"
    "                if(msg){msg.style.color='#32d74b';msg.textContent='HTML copied — paste into Claude.ai to refine';}\n"
    "                setTimeout(function(){if(btn)btn.innerHTML='⍘ Copy HTML<span class=\"pm-link-tag\">claude</span>';},2500);\n"
    "              }).catch(function(){\n"
    "                _fbCopy(text);\n"
    "                if(msg){msg.style.color='#32d74b';msg.textContent='HTML copied — paste into Claude.ai to refine';}\n"
    "              });\n"
    "            } else { _fbCopy(text); if(msg){msg.style.color='#32d74b';msg.textContent='HTML copied';} }\n"
    "          } else {\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+((r&&r.error)||'unknown');}\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(err){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='⍘ Copy HTML<span class=\"pm-link-tag\">claude</span>';}\n"
    "          if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+(err&&err.message?err.message:String(err));}\n"
    "        })\n"
    "        .getDesignHtml(assetId);",
    "      gasCall({action:'get_design_html', asset_id:assetId, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='⍘ Copy HTML<span class=\"pm-link-tag\">claude</span>';}\n"
    "          if(r&&r.html){\n"
    "            var text=r.html;\n"
    "            if(navigator.clipboard&&navigator.clipboard.writeText){\n"
    "              navigator.clipboard.writeText(text).then(function(){\n"
    "                if(btn)btn.innerHTML='✓ Copied!<span class=\"pm-link-tag\">claude</span>';\n"
    "                if(msg){msg.style.color='#32d74b';msg.textContent='HTML copied — paste into Claude.ai to refine';}\n"
    "                setTimeout(function(){if(btn)btn.innerHTML='⍘ Copy HTML<span class=\"pm-link-tag\">claude</span>';},2500);\n"
    "              }).catch(function(){\n"
    "                _fbCopy(text);\n"
    "                if(msg){msg.style.color='#32d74b';msg.textContent='HTML copied — paste into Claude.ai to refine';}\n"
    "              });\n"
    "            } else { _fbCopy(text); if(msg){msg.style.color='#32d74b';msg.textContent='HTML copied';} }\n"
    "          } else {\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+((r&&r.error)||'unknown');}\n"
    "          }\n"
    "        })\n"
    "        .catch(function(err){\n"
    "          if(btn){btn.disabled=false;btn.innerHTML='⍘ Copy HTML<span class=\"pm-link-tag\">claude</span>';}\n"
    "          if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+(err&&err.message?err.message:String(err));}\n"
    "        });"
))

# ── 19. saveDesignToDrive ─────────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(r&&r.ok&&r.url){\n"
    "            if(POST_REGISTRY[assetId])POST_REGISTRY[assetId].claude_design_url=r.url;\n"
    "            if(msg){msg.style.color='#32d74b';msg.textContent='✓ Saved';}\n"
    "            if(btn)btn.disabled=false;\n"
    "            setTimeout(function(){openPostModal(assetId);},600);\n"
    "          } else {\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+((r&&r.error)||'unknown');}\n"
    "            if(btn)btn.disabled=false;\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(){if(btn)btn.disabled=false;if(msg){msg.style.color='#ff453a';msg.textContent='Connection error';}})\n"
    "        .saveDesignToDrive(assetId, html);",
    "      gasCall({action:'save_design_to_drive', asset_id:assetId, html:html, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(r&&r.ok&&r.url){\n"
    "            if(POST_REGISTRY[assetId])POST_REGISTRY[assetId].claude_design_url=r.url;\n"
    "            if(msg){msg.style.color='#32d74b';msg.textContent='✓ Saved';}\n"
    "            if(btn)btn.disabled=false;\n"
    "            setTimeout(function(){openPostModal(assetId);},600);\n"
    "          } else {\n"
    "            if(msg){msg.style.color='#ff453a';msg.textContent='Error: '+((r&&r.error)||'unknown');}\n"
    "            if(btn)btn.disabled=false;\n"
    "          }\n"
    "        })\n"
    "        .catch(function(){if(btn)btn.disabled=false;if(msg){msg.style.color='#ff453a';msg.textContent='Connection error';}});"
))

# ── 20. appendContentCalNote (includes fire-and-forget Klaviyo + Figma) ───────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(r&&r.ok){\n"
    "            if(POST_REGISTRY[assetId]) POST_REGISTRY[assetId].notes=r.result.notes;\n"
    "            openPostModal(assetId);\n"
    "            var m=document.getElementById('pm-note-msg');\n"
    "            if(m){m.style.color='#32d74b';m.textContent='✓ Note added';}\n"
    "            // Fire Klaviyo + Figma in the background — best effort, non-blocking\n"
    "            var p=POST_REGISTRY[assetId]||{};\n"
    "            var sheetUrl=SHEET_ID&&SHEET_GID&&p.sheet_row?'https://docs.google.com/spreadsheets/d/'+SHEET_ID+'/edit#gid='+SHEET_GID+'&range=A'+p.sheet_row:'';\n"
    "            google.script.run.klaviyoTrackNote(assetId,p.platform||'',text,author,p.brief_doc_url||'',sheetUrl);\n"
    "            if(p.figma_url) google.script.run.figmaPostComment(p.figma_url,'['+author+'] '+text);\n"
    "          } else {\n"
    "            if(btn) btn.disabled=false;\n"
    "            var m=document.getElementById('pm-note-msg');\n"
    "            if(m){m.style.color='#ff453a';m.textContent='Error: '+(r&&r.result&&r.result.error?r.result.error:'unknown');}\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(){\n"
    "          if(btn) btn.disabled=false;\n"
    "          var m=document.getElementById('pm-note-msg');\n"
    "          if(m){m.style.color='#ff453a';m.textContent='Connection error';}\n"
    "        })\n"
    "        .appendContentCalNote(assetId, text, author);",
    "      gasCall({action:'append_content_cal_note', asset_id:assetId, text:text, author:author, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(r&&r.ok){\n"
    "            if(POST_REGISTRY[assetId]) POST_REGISTRY[assetId].notes=r.result.notes;\n"
    "            openPostModal(assetId);\n"
    "            var m=document.getElementById('pm-note-msg');\n"
    "            if(m){m.style.color='#32d74b';m.textContent='✓ Note added';}\n"
    "            // Fire Klaviyo + Figma in the background — best effort, non-blocking\n"
    "            var p=POST_REGISTRY[assetId]||{};\n"
    "            var sheetUrl=SHEET_ID&&SHEET_GID&&p.sheet_row?'https://docs.google.com/spreadsheets/d/'+SHEET_ID+'/edit#gid='+SHEET_GID+'&range=A'+p.sheet_row:'';\n"
    "            gasCall({action:'klaviyo_track_note', asset_id:assetId, platform:p.platform||'', text:text, author:author, brief_doc_url:p.brief_doc_url||'', sheet_url:sheetUrl});\n"
    "            if(p.figma_url) gasCall({action:'figma_post_comment', figma_url:p.figma_url, comment:'['+author+'] '+text});\n"
    "          } else {\n"
    "            if(btn) btn.disabled=false;\n"
    "            var m=document.getElementById('pm-note-msg');\n"
    "            if(m){m.style.color='#ff453a';m.textContent='Error: '+(r&&r.result&&r.result.error?r.result.error:'unknown');}\n"
    "          }\n"
    "        })\n"
    "        .catch(function(){\n"
    "          if(btn) btn.disabled=false;\n"
    "          var m=document.getElementById('pm-note-msg');\n"
    "          if(m){m.style.color='#ff453a';m.textContent='Connection error';}\n"
    "        });"
))

# ── 21. updateContentCalField (includes fire-and-forget Klaviyo) ──────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(r&&r.ok){\n"
    "            if(POST_REGISTRY[assetId]) POST_REGISTRY[assetId][field]=value;\n"
    "            openPostModal(assetId);\n"
    "            var m=document.getElementById('pm-save-msg');\n"
    "            if(m){m.style.color='#32d74b';m.textContent='✓ Saved';}\n"
    "            setTimeout(function(){if(calData)applyAndRender();},600);\n"
    "            // Fire Klaviyo status event — best effort\n"
    "            var p=POST_REGISTRY[assetId]||{};\n"
    "            var sheetUrl=SHEET_ID&&SHEET_GID&&p.sheet_row?'https://docs.google.com/spreadsheets/d/'+SHEET_ID+'/edit#gid='+SHEET_GID+'&range=A'+p.sheet_row:'';\n"
    "            google.script.run.klaviyoTrackStatusUpdate(assetId,p.platform||'',field,value,p.brief_doc_url||'',sheetUrl);\n"
    "          } else {\n"
    "            var m=document.getElementById('pm-save-msg');\n"
    "            if(m){m.style.color='#ff453a';m.textContent='Error: '+(r&&r.error?r.error:'unknown');}\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(e){\n"
    "          var m=document.getElementById('pm-save-msg');\n"
    "          if(m){m.style.color='#ff453a';m.textContent='Connection error';}\n"
    "        })\n"
    "        .updateContentCalField(assetId, field, value);",
    "      gasCall({action:'update_content_cal_field', asset_id:assetId, field:field, value:value, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(r&&r.ok){\n"
    "            if(POST_REGISTRY[assetId]) POST_REGISTRY[assetId][field]=value;\n"
    "            openPostModal(assetId);\n"
    "            var m=document.getElementById('pm-save-msg');\n"
    "            if(m){m.style.color='#32d74b';m.textContent='✓ Saved';}\n"
    "            setTimeout(function(){if(calData)applyAndRender();},600);\n"
    "            // Fire Klaviyo status event — best effort\n"
    "            var p=POST_REGISTRY[assetId]||{};\n"
    "            var sheetUrl=SHEET_ID&&SHEET_GID&&p.sheet_row?'https://docs.google.com/spreadsheets/d/'+SHEET_ID+'/edit#gid='+SHEET_GID+'&range=A'+p.sheet_row:'';\n"
    "            gasCall({action:'klaviyo_track_status', asset_id:assetId, platform:p.platform||'', field:field, value:value, brief_doc_url:p.brief_doc_url||'', sheet_url:sheetUrl});\n"
    "          } else {\n"
    "            var m=document.getElementById('pm-save-msg');\n"
    "            if(m){m.style.color='#ff453a';m.textContent='Error: '+(r&&r.error?r.error:'unknown');}\n"
    "          }\n"
    "        })\n"
    "        .catch(function(e){\n"
    "          var m=document.getElementById('pm-save-msg');\n"
    "          if(m){m.style.color='#ff453a';m.textContent='Connection error';}\n"
    "        });"
))

# ── 22. getCampaignDashboard ──────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){if(r&&r.ok){dashData=r;if(!hasFilters()){var all=getAllPosts();renderDash(r,all);}}else{document.getElementById('panel-dash').innerHTML='<div class=\"loading\">Error.</div><button class=\"btn\" onclick=\"load()\" style=\"margin-top:12px\">&#8635; Retry</button>';} })\n"
    "        .withFailureHandler(function(){document.getElementById('panel-dash').innerHTML='<div class=\"loading\">Connection error.</div><button class=\"btn\" onclick=\"load()\" style=\"margin-top:12px\">&#8635; Retry</button>';})\n"
    "        .getCampaignDashboard(_activeCampaign, _activeSheetId);",
    "      gasCall({action:'get_campaign_dashboard', campaign_id:_activeCampaign, sheet_id:_activeSheetId})\n"
    "        .then(function(r){if(r&&r.ok){dashData=r;if(!hasFilters()){var all=getAllPosts();renderDash(r,all);}}else{document.getElementById('panel-dash').innerHTML='<div class=\"loading\">Error.</div><button class=\"btn\" onclick=\"load()\" style=\"margin-top:12px\">&#8635; Retry</button>';} })\n"
    "        .catch(function(){document.getElementById('panel-dash').innerHTML='<div class=\"loading\">Connection error.</div><button class=\"btn\" onclick=\"load()\" style=\"margin-top:12px\">&#8635; Retry</button>';});"
))

# ── 23. getCampaignCalendar ───────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(r&&r.ok){\n"
    "            calData=r;\n"
    "            if(r.sheet_id)SHEET_ID=r.sheet_id;\n"
    "            if(r.sheet_gid!==undefined)SHEET_GID=String(r.sheet_gid);\n"
    "            if(r.drive_folder_url)DRIVE_FOLDER_URL=r.drive_folder_url;\n"
    "            if(r.lp_links)CAMPAIGN_LP_LINKS=r.lp_links;\n"
    "            if(r.roadmap_url)ROADMAP_URL=r.roadmap_url;\n"
    "            if(r.campaign_ids) _populateCampaignSelect(r.campaign_ids);\n"
    "            if(!SEQ_DEFS.length) _rebuildSeqDefs();\n"
    "            applyAndRender();\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(){})\n"
    "        .getCampaignCalendar(_activeCampaign, _activeSheetId);",
    "      gasCall({action:'get_campaign_calendar', campaign_id:_activeCampaign, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(r&&r.ok){\n"
    "            calData=r;\n"
    "            if(r.sheet_id)SHEET_ID=r.sheet_id;\n"
    "            if(r.sheet_gid!==undefined)SHEET_GID=String(r.sheet_gid);\n"
    "            if(r.drive_folder_url)DRIVE_FOLDER_URL=r.drive_folder_url;\n"
    "            if(r.lp_links)CAMPAIGN_LP_LINKS=r.lp_links;\n"
    "            if(r.roadmap_url)ROADMAP_URL=r.roadmap_url;\n"
    "            if(r.campaign_ids) _populateCampaignSelect(r.campaign_ids);\n"
    "            if(!SEQ_DEFS.length) _rebuildSeqDefs();\n"
    "            applyAndRender();\n"
    "          }\n"
    "        })\n"
    "        .catch(function(){});"
))

# ── 24. seedAllCampaignsContentCalendar ───────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          var btn2=document.getElementById('cal-sync-btn');\n"
    "          if(btn2){btn2.disabled=false;btn2.textContent='↻ Sync';}\n"
    "          if(r&&r.ok){\n"
    "            var msg='✓ Seeded '+(r.total_seeded||0)+' posts';\n"
    "            var flash=document.getElementById('cal-sync-msg');\n"
    "            if(flash){flash.textContent=msg;flash.style.color='#32d74b';setTimeout(function(){flash.textContent='';},4000);}\n"
    "            loadCalendar();\n"
    "          } else {\n"
    "            var flash2=document.getElementById('cal-sync-msg');\n"
    "            if(flash2){flash2.textContent='Error: '+((r&&r.error)||'unknown');flash2.style.color='#ff453a';}\n"
    "            loadCalendar();\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(e){\n"
    "          var btn3=document.getElementById('cal-sync-btn');\n"
    "          if(btn3){btn3.disabled=false;btn3.textContent='↻ Sync';}\n"
    "          var flash3=document.getElementById('cal-sync-msg');\n"
    "          if(flash3){flash3.textContent='Connection error';flash3.style.color='#ff453a';}\n"
    "          loadCalendar();\n"
    "        })\n"
    "        .seedAllCampaignsContentCalendar();",
    "      gasCall({action:'seed_all_campaigns_content_calendar', sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          var btn2=document.getElementById('cal-sync-btn');\n"
    "          if(btn2){btn2.disabled=false;btn2.textContent='↻ Sync';}\n"
    "          if(r&&r.ok){\n"
    "            var msg='✓ Seeded '+(r.total_seeded||0)+' posts';\n"
    "            var flash=document.getElementById('cal-sync-msg');\n"
    "            if(flash){flash.textContent=msg;flash.style.color='#32d74b';setTimeout(function(){flash.textContent='';},4000);}\n"
    "            loadCalendar();\n"
    "          } else {\n"
    "            var flash2=document.getElementById('cal-sync-msg');\n"
    "            if(flash2){flash2.textContent='Error: '+((r&&r.error)||'unknown');flash2.style.color='#ff453a';}\n"
    "            loadCalendar();\n"
    "          }\n"
    "        })\n"
    "        .catch(function(e){\n"
    "          var btn3=document.getElementById('cal-sync-btn');\n"
    "          if(btn3){btn3.disabled=false;btn3.textContent='↻ Sync';}\n"
    "          var flash3=document.getElementById('cal-sync-msg');\n"
    "          if(flash3){flash3.textContent='Connection error';flash3.style.color='#ff453a';}\n"
    "          loadCalendar();\n"
    "        });"
))

# ── 25. repairCreativeStatus ──────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          var msg=r&&r.ok?('✓ Fixed '+(r.result&&r.result.fixed||0)+' rows — reloading…'):'Repair failed.';\n"
    "          var color=r&&r.ok?'#32d74b':'#ff453a';\n"
    "          if(btn){btn.disabled=false;btn.textContent=msg;btn.style.color=color;btn.style.borderColor=color;}\n"
    "          if(r&&r.ok){setTimeout(function(){load();},1500);}\n"
    "        })\n"
    "        .withFailureHandler(function(){\n"
    "          if(btn){btn.disabled=false;btn.textContent='Repair error';btn.style.color='#ff453a';}\n"
    "        })\n"
    "        .repairCreativeStatus(_activeCampaign);",
    "      gasCall({action:'repair_creative_status', campaign_id:_activeCampaign, sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          var msg=r&&r.ok?('✓ Fixed '+(r.result&&r.result.fixed||0)+' rows — reloading…'):'Repair failed.';\n"
    "          var color=r&&r.ok?'#32d74b':'#ff453a';\n"
    "          if(btn){btn.disabled=false;btn.textContent=msg;btn.style.color=color;btn.style.borderColor=color;}\n"
    "          if(r&&r.ok){setTimeout(function(){load();},1500);}\n"
    "        })\n"
    "        .catch(function(){\n"
    "          if(btn){btn.disabled=false;btn.textContent='Repair error';btn.style.color='#ff453a';}\n"
    "        });"
))

# ── 26. generateContentCalBriefDocs ──────────────────────────────────────────
replacements.append((
    "        google.script.run\n"
    "          .withSuccessHandler(function(r){\n"
    "            if(r&&r.ok){\n"
    "              _total+=(r.created||0);\n"
    "              if(r.remaining>0){\n"
    "                if(btn)btn.textContent='⏳ '+_total+' done, '+r.remaining+' left…';\n"
    "                setTimeout(_run,400);\n"
    "              } else {\n"
    "                var msg='✓ '+_total+' URLs populated'+(r.skipped?' ('+r.skipped+' already set)':'')+' — reloading…';\n"
    "                if(btn){btn.disabled=false;btn.textContent=msg;btn.style.color='#32d74b';btn.style.borderColor='#32d74b';}\n"
    "                setTimeout(function(){load();},1800);\n"
    "              }\n"
    "            } else {\n"
    "              if(btn){btn.disabled=false;btn.textContent='Error — see logs';btn.style.color='#ff453a';}\n"
    "            }\n"
    "          })\n"
    "          .withFailureHandler(function(e){\n"
    "            if(btn){btn.disabled=false;btn.textContent='Failed: '+(e&&e.message||'unknown');btn.style.color='#ff453a';}\n"
    "          })\n"
    "          .generateContentCalBriefDocs(_activeCampaign,{force:!!force});",
    "        gasCall({action:'generate_content_cal_brief_docs', campaign_id:_activeCampaign, force:!!force, sheet_id:_activeSheetId})\n"
    "          .then(function(r){\n"
    "            if(r&&r.ok){\n"
    "              _total+=(r.created||0);\n"
    "              if(r.remaining>0){\n"
    "                if(btn)btn.textContent='⏳ '+_total+' done, '+r.remaining+' left…';\n"
    "                setTimeout(_run,400);\n"
    "              } else {\n"
    "                var msg='✓ '+_total+' URLs populated'+(r.skipped?' ('+r.skipped+' already set)':'')+' — reloading…';\n"
    "                if(btn){btn.disabled=false;btn.textContent=msg;btn.style.color='#32d74b';btn.style.borderColor='#32d74b';}\n"
    "                setTimeout(function(){load();},1800);\n"
    "              }\n"
    "            } else {\n"
    "              if(btn){btn.disabled=false;btn.textContent='Error — see logs';btn.style.color='#ff453a';}\n"
    "            }\n"
    "          })\n"
    "          .catch(function(e){\n"
    "            if(btn){btn.disabled=false;btn.textContent='Failed: '+(e&&e.message||'unknown');btn.style.color='#ff453a';}\n"
    "          });"
))

# ── 27. figmaTokenStatus ──────────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(!r||!r.set) return;\n"
    "          var days=r.days_left;\n"
    "          if(days>14) return;\n"
    "          var msg = days<=0\n"
    "            ? 'Figma API token has EXPIRED — Figma comments are offline. Rotate it in Script Properties and run figmaRecordTokenExpiry().'\n"
    "            : 'Figma API token expires in '+days+' day'+(days!==1?'s':'')+'. Rotate it soon to keep Figma comments working.';\n"
    "          var bar=document.createElement('div');\n"
    "          bar.id='figma-token-bar';\n"
    "          bar.style.cssText='position:fixed;top:0;left:0;right:0;z-index:9999;background:'+(days<=0?'#c0392b':'#e67e22')+';color:#fff;font:600 13px/1 system-ui;padding:9px 48px 9px 16px;text-align:center;';\n"
    "          bar.textContent=msg;\n"
    "          var x=document.createElement('span');\n"
    "          x.textContent='✕';\n"
    "          x.style.cssText='position:absolute;right:14px;top:50%;transform:translateY(-50%);cursor:pointer;font-size:16px;';\n"
    "          x.onclick=function(){bar.remove();};\n"
    "          bar.appendChild(x);\n"
    "          document.body.prepend(bar);\n"
    "        })\n"
    "        .withFailureHandler(function(){})\n"
    "        .figmaTokenStatus();",
    "      gasCall({action:'check_figma_token'})\n"
    "        .then(function(r){\n"
    "          if(!r||!r.set) return;\n"
    "          var days=r.days_left;\n"
    "          if(days>14) return;\n"
    "          var msg = days<=0\n"
    "            ? 'Figma API token has EXPIRED — Figma comments are offline. Rotate it in Script Properties and run figmaRecordTokenExpiry().'\n"
    "            : 'Figma API token expires in '+days+' day'+(days!==1?'s':'')+'. Rotate it soon to keep Figma comments working.';\n"
    "          var bar=document.createElement('div');\n"
    "          bar.id='figma-token-bar';\n"
    "          bar.style.cssText='position:fixed;top:0;left:0;right:0;z-index:9999;background:'+(days<=0?'#c0392b':'#e67e22')+';color:#fff;font:600 13px/1 system-ui;padding:9px 48px 9px 16px;text-align:center;';\n"
    "          bar.textContent=msg;\n"
    "          var x=document.createElement('span');\n"
    "          x.textContent='✕';\n"
    "          x.style.cssText='position:absolute;right:14px;top:50%;transform:translateY(-50%);cursor:pointer;font-size:16px;';\n"
    "          x.onclick=function(){bar.remove();};\n"
    "          bar.appendChild(x);\n"
    "          document.body.prepend(bar);\n"
    "        })\n"
    "        .catch(function(){});"
))

# ── 28. addCampaignMilestone ──────────────────────────────────────────────────
replacements.append((
    "      google.script.run\n"
    "        .withSuccessHandler(function(r){\n"
    "          if(r&&r.ok){\n"
    "            msg.style.color='#32d74b'; msg.textContent='Milestone added!';\n"
    "            setTimeout(function(){ closeMsModal(); loadMilestones(); },900);\n"
    "          } else {\n"
    "            msg.style.color='#ff453a'; msg.textContent='Error saving.'; btn.disabled=false;\n"
    "          }\n"
    "        })\n"
    "        .withFailureHandler(function(e){\n"
    "          msg.style.color='#ff453a'; msg.textContent='Error: '+(e&&e.message?e.message:'unknown'); btn.disabled=false;\n"
    "        })\n"
    "        .addCampaignMilestone({\n"
    "          title:title, date:date, color:_msCurColor,\n"
    "          type:'custom', campaign_id:_activeCampaign||'EC-2026-001', created_by:author\n"
    "        });",
    "      gasCall({action:'add_milestone',\n"
    "          title:title, date:date, color:_msCurColor,\n"
    "          type:'custom', campaign_id:_activeCampaign||'EC-2026-001', created_by:author,\n"
    "          sheet_id:_activeSheetId})\n"
    "        .then(function(r){\n"
    "          if(r&&r.ok){\n"
    "            msg.style.color='#32d74b'; msg.textContent='Milestone added!';\n"
    "            setTimeout(function(){ closeMsModal(); loadMilestones(); },900);\n"
    "          } else {\n"
    "            msg.style.color='#ff453a'; msg.textContent='Error saving.'; btn.disabled=false;\n"
    "          }\n"
    "        })\n"
    "        .catch(function(e){\n"
    "          msg.style.color='#ff453a'; msg.textContent='Error: '+(e&&e.message?e.message:'unknown'); btn.disabled=false;\n"
    "        });"
))

# Apply all replacements
errors = []
for i, (old, new) in enumerate(replacements, 1):
    if old in out:
        out = out.replace(old, new, 1)
        print(f'OK {i}: replaced')
    else:
        errors.append(i)
        print(f'WARN {i}: NOT FOUND')

with open(path, 'w', encoding='utf-8') as f:
    f.write(out)

remaining = out.count('google.script.run')
print(f'\nRemaining google.script.run: {remaining}')
print(f'Errors: {errors}')
print(f'Size: {len(out):,} chars')
